export const GET_SEARCH_RESULT_REQUEST = 'GET_SEARCH_RESULT_REQUEST';
export const GET_SEARCH_RESULT_SUCCESS = 'GET_SEARCH_RESULT_SUCCESS';
export const GET_SEARCH_RESULT_FAILURE = 'GET_SEARCH_RESULT_FAILURE';
export const CLEAN_SEARCH_STATES = 'CLEAN_SEARCH_STATES';

export const GET_QUESTION_SUCCESS = 'GET_QUESTION_SUCCESS';
export const GET_QUESTION_REQUEST = 'GET_QUESTION_REQUEST';
export const GET_QUESTION_FAILURE = 'GET_QUESTION_FAILURE';